baseURL: https://edward-davies-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Edward Davies
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: About Me
    url: https://edward-davies-portfolio.netlify.app/about-me/  # <-- Change '/your-page' to the relative URL of your target page
    title: Hi, my name is Edward Davies.
  # The rest of your parameters go here...
  footer:
    # The rest of your footer parameters go here...
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/edward.davies.712714
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/edxdavies/
      - icon: fa-github
        label: GitHub
        url: https://github.com/edwardhdavies
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/edwardhdavies/  # <-- replace with your LinkedIn URL
  # The rest of your parameters go here...
  navigation:
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: About Me
        url: about-me  # This should link to the page you want to navigate to when "Get Started" is clicked
