baseURL: https://edward-davies-portfolio.netlify.app
languageCode: en-us
title: Edward Davies
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    subtitle: |-
      Welcome to my website. Feel free to have a look at my resume, as well as some of my datascience projects!
    title: Edward Henry Davies
  blog: {}
  contact:
    address:
      - city: ...soon to be...
        country: Berlin, Germany 
        street: London, UK
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: edwardhdavies@outlook.com
        title: Email
    enable: yes
    phone:
      - phone: +(44)7738612624
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Edward Davies, 2023
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/edward.davies.712714
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/edxdavies/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/edwardhdavies
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/edwardhdavies
  image: ''
  name: Your name
  navigation:
    button1:
#      - name: Get Started
#        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Portfolio
        url: blogs
      - name: Resume
        url: resume
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
#    menu: Menu
#    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: h1_cover.png
        subtitle: Investigating the Love Interests within Hollywood movie datasets, and the trends amoungst them
        title: The Love Interests of Hollywood
        url: blogs/homework1_web
      - image: h2_cover.png
        subtitle: Investigating a flights database, and manipulating dataframes to tackle specific goals
        title: Flights, Flights, Flights!
        url: blogs/homework2_web
#      - image: pic03.jpg
#        subtitle: Lorem Etiam Nullam
#        title: Project 3
#        url: blogs/magna
#      - image: pic04.jpg
#        subtitle: Nisl Sed Aliquam
#        title: Project 4
#        url: blogs/ipsum
  #    - image: pic05.jpg
  #      subtitle: Ipsum Dolor Sit Amet
  #      title: Consequat
  #      url: blogs/ipsum
  #    - image: pic06.jpg
  #      subtitle: Feugiat Amet Tempus
  #      title: Etiam
  #      url: blogs/ipsum
#  two:
#    buttonText: Get Started
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#    title: Massa libero
#    url: blogs
