baseURL: https://edward-davies-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Edward Davies
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    # subtitle: |-
    # A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    # AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Edward Davies.
  blog: {}
  contact:
  email: edwardhdavies@outlook.com
  buttonClear: Clear
  buttonSend: Send message
  email:
    - email: example@domain.com
      title: Email
  enable: yes
  phone:
    - phone: (000) 000-0000 x1234
      title: Phone
...
